name: Ngenix_can Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # каждые 6 часов

jobs:
  scan-ngenix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run Ngenix_can scanner
        run: |
          python ngenix_can.py

      - name: Commit playlist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ngenix_can.m3u
          git commit -m "Ngenix_can playlist update" || echo "No changes"
          git push